name: ryu-cho

on:
  # Schedule the interval of the checks.
  schedule:
    - cron: '0 0 * * *'

jobs:
  ryu-cho:
    name: Ryu Cho
    runs-on: ubuntu-latest
    steps:
      - uses: vuejs-translations/ryu-cho@v1
        with:
          # GitHub access token. Required.
          access-token: ${{ secrets.UPSTREAM_SYNC_TOKEN }}

          # Git user name to use when making issues and PRs. Required.
          username: ${{ secrets.UPSTREAM_SYNC_USERNANE }}

          # Git email address to use when making issues and PRs. Required.
          email: ${{ secrets.UPSTREAM_SYNC_EMAIL }}

          # The url for the upstream repo. This is the repository that you
          # set up Ryu-Cho. Required.
          upstream-repo: https://github.com/translation-ru/pinia.git

          # The branch for the upstream repo. Optional. Defaults to `main`.
          upstream-repo-branch: v2

          # The head repo to track. This is the repository you want to
          # take a diff. Required.
          head-repo: https://github.com/vuejs/pinia

          # The branch for the head repo. Optional. Defaults to `main`.
          head-repo-branch: v2

          # The git commit sha of head repo to start tracking. Ryu-Cho will
          # only track commit from this hash. Required.
          track-from: 498cff1a2620c313fe7c117c1f2f5258fa16f13e

          # File path to track. In this example, Ryu-Cho will only track
          # commits that modified files under `docs` folder. Optional.
          path-starts-with: packages/docs

          # GitHub workflow name that runs Ryu-Cho. This is required since
          # Ryu-Cho determines the last run by looking into last workflow
          # run timestamp. Optional. Defaults to `ryu-cho`.
          workflow-name: ryu-cho
